apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-python-demo
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      service: flask
  template:
    metadata:
      labels:
        service: flask
    spec:
      containers:
        - name: flask-service
          image: longshot101/python-devops
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword

---
apiVersion: v1
kind: Service
metadata:
  name: service-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    service: flask
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001